app/models.py
from datetime import datetime
from flask import current_app
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask_login import UserMixin
from . import db, login_manager


# AuctionSite table
class AuctionSite(db.Model):
	__tablename__ = 'auction_sites'
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(64), unique=True)
	wines = db.relationship('Listing', backref='auction_sites')


# Listing table
class Listing(db.Model):
	__tablename__ = 'listings'
	id = db.Column(db.Integer, primary_key=True)
	year = db.Column(db.Integer, index=True)
	producer = db.Column(db.String(256), index=True)
	alert = db.Column(db.String(64), default=None)
	price = db.Column(db.String(16))
	old_price = db.Column(db.String(16), default=None)
	time_added = db.Column(db.DateTime, default=datetime.utcnow())
	time_removed = db.Column(db.DateTime, default=None)
	active = db.Column(db.Boolean, default=True)
	item_code = db.Column(db.String(32))
	site_id = db.Column(db.Integer, db.ForeignKey('auction_sites.id'))


# User table
class User(UserMixin, db.Model):
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(64), unique=True, index=True)
	email = db.Column(db.String(64), unique=True, index=True)
	password_hash = db.Column(db.String(128))

	# True if user has clicked confirmation link, False otherwise
	confirmed = db.Column(db.Boolean, default=False)

	# Generates confirmation token using JSON Web Signature Serializer
	def generate_confirmation_token(self, expiration=3600):
		s = Serializer(current_app.config['SECRET_KEY'], expiration)
		return s.dumps({'confirm': self.id})
		
	# Confirms token's validity
	def confirm(self, token):
		s = Serializer(current_app.config['SECRET_KEY'])
		try:
			data = s.loads(token)
		except:
			return False
		if data.get('confirm') != self.id:
			return False
		self.confirmed = True
		db.session.add(self)
		return True

	@login_manager.user_loader
	def load_user(user_id):
		return User.query.get(int(user_id))

	@property
	def password(self):
		raise AttributeError('password is not a readable attribute')

	@password.setter
	def password(self, password):
		self.password_hash = generate_password_hash(password)

	def verify_password(self, password):
		return check_password_hash(self.password_hash, password)

	def __repr__(self):
		return '<%r>' % self.username
		

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField


# Form for search page
class SearchForm(FlaskForm):
	producer = StringField("Producer")
	year = SelectField(
			label='Year',
			choices=[tuple([i,i]) for i in range(2017, 1950, -1)], coerce=int
	)
	search = SubmitField("Search")

app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
from flask_login import LoginManager
from config import config


bootstrap = Bootstrap()
mail = Mail()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
	'''
	Application Factory function.
	Parameter is the name of the chosen configuration.
	'''
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	config[config_name].init_app(app)

	# Finish initializing add-ons
	bootstrap.init_app(app)
	mail.init_app(app)
	db.init_app(app)
	login_manager.init_app(app)

	# Register blueprints with application
	from .main import main as main_blueprint
	from .auth import auth as auth_blueprint
	app.register_blueprint(main_blueprint)
	app.register_blueprint(auth_blueprint)
	
	return app

app/main/__init__.py
from flask import Blueprint

# Create main blueprint
main = Blueprint('main', __name__)

# Associate all views in main with main blueprint
from . import views

app/main/views.py
from flask import render_template, redirect, url_for, session
from flask_login import login_required
from .forms import SearchForm
from . import main
from ..scrape import scrape_all


# Front page
@main.route('/', methods=['GET'])
def index():
	return render_template('index.html')


# Handles user search input
@main.route('/search', methods=['GET', 'POST'])
@login_required
def search():
	scrape_all()
	producer = None 
	year = None
	form = SearchForm()

	# If handling a POST request, set values for the session and redirect
	if form.validate_on_submit():
		session['producer'] = form.producer.data
		session['year'] = form.year.data
		return redirect(url_for('.search'))

	# If handling a GET request, render the template 
	return render_template('search.html', form=form, producer=session.get('producer'), year=session.get('year'))

app/templates/base.html
{% extends "bootstrap/base.html" %}
<link rel="stylesheet" href="styles.css">

{% block title %}Wine Aid{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle"
			 data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">Wine Aid</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="/">Home</a></li>
			</ul>
			<ul class="navbar-nav navbar-right">
				{% if current_user.is_authenticated %}
				<li><a href="{{ url_for('auth.logout') }}">Sign Out</a></li>
				{% else %}
				<li><a href="{{ url_for('auth.login') }}">Sign In</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</div>
{% endblock %}

{% block content %}
<div class="container">
	{% for message in get_flashed_messages() %}
	<div class="alert alert-warning">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		{{ message }}
	</div>
	{% endfor %}

	{% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/form_bs.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block body %}
	<h1>
	{% if producer %}
		Searching for {{ year }} {{ producer }}.
	{% else %}
		Enter search criteria.
	{% endif %}
	</h1>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block page_content %}
	<h1>Wine Scraper</h1>
	<a href="{{ url_for('auth.register') }}">Sign Up</a>
	<br>
	<a href="{{ url_for('auth.login') }}">Log In</a>
	<br>
	<a href="{{ url_for('main.search') }}" class="btn btn-info" role="button">Scrape</a>

{% endblock %}

app/templates/search.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
	<h1>
	{% if producer %}
		Searching for {{ year }} {{ producer }}.
	{% else %}
		Enter search criteria.
	{% endif %}
	</h1>
{{ wtf.quick_form(form) }}

<div class='search_table'>
		<table class="table">
			<thead>
				<tr>
					<th>Auction Site</th>
					<th>Year</th>
					<th>Producer</th>
					<th>Additional Information</th>
					<th>Price</th>
				</tr>
			</thead>
		</table>
</div>
{% endblock %}